### ISSUE TITLE
Incorrect Parsing of Authority Part in URLs Containing Special Characters

### ISSUE THREAD

**Issue by sibicode** [slevithan/parseuri#1]
There is an issue with parsing the authority part of the URL wich not correctly determined if the domain part contains special characters such as `#`, `/`, or `\`. 
This results in the authority part being identified only up to the special character, leading to incorrect parsing.

Example:
`http://exa/mple.com/path`. With other special characters works correctly.

Expected Behavior:
The authority part should be correctly identified as the full domain part in this case `example.com`

Actual Behavior:
For `http://exa/mple.com/path` the authority part is identified as `exa`.

**Comment by slevithan** [comment]
> There is an issue with parsing the authority part of the URL wich not correctly determined if the domain part contains special characters such as `#`, `/`, or `\`.

Those are among the characters that mark the end of an authority.

> Example: `http://exa/mple.com/path`. With other special characters works correctly.
> 
> Expected Behavior: The authority part should be correctly identified as the full domain part in this case `example.com`
> 
> Actual Behavior: For `http://exa/mple.com/path` the authority part is identified as `exa`.

The authority is correctly identified as `exa`, and `/mple.com` is correctly identified as part of the pathname.

You can see on the demo page that `parseUri` handles this *the same* as URI.js and JavaScript's native `URL` constructor: [Demo: http://exa/mple.com/path](https://slevithan.github.io/parseuri/demo/?friendlyMode=true&uri=http%3A%2F%2Fexa%2Fmple.com%2Fpath&urlStandard=true&uriJs=true).

**Comment by sibicode** [comment]
[slevithan](https://github.com/slevithan)
Thanks for the quick reply, so is this the correct behavior or is the library copying URI.js logic ? 
Is it possible to process this in any way? I would like to process such a case to check the entered domain and show an error, in this case about a wrong character in the domain.

I also noticed that in the example [http://exa\mple.com/path](https://slevithan.github.io/parseuri/demo/?uri=http%3A%2F%2Fexa%5Cmple.com%2Fpath&uriJs=true) URI.js replaces `\` with `/`.

**Comment by slevithan** [comment]
> so is this the correct behavior or is the library copying URI.js logic ?

It is correct behavior, unrelated to any other libraries.

> Is it possible to process this in any way? I would like to process such a case to check the entered domain and show an error, in this case about a wrong character in the domain.

But there is no incorrect/invalid character in the domain. Hostnames do not need to include a dot (a common example is "localhost"), and every OS I'm aware of allows dots in directory/folder names (as with "/mple.com/" in your example). Various characters definitively indicate the end of the hostname, and these include the characters you mentioned.

So I'm not sure what to suggest. You would not be merely extending parsing logic by introducing such an error--you would be disregarding the standard structure of URIs and making your code incompatible with perfectly valid URIs.

Perhaps you could check whether `parseUri(str).hostname` includes a dot, and throw if it doesn't. Then you'd merely be limiting yourself to a subset of valid hostnames.

> I also noticed that in the example [http://exa\mple.com/path](https://slevithan.github.io/parseuri/demo/?uri=http%3A%2F%2Fexa%5Cmple.com%2Fpath&uriJs=true) URI.js replaces `\` with `/`.

URI.js parses and *normalizes* URIs, which is where the difference comes from with `\`. `parseUri` is single-purpose and only parses URIs--it doesn't change them. If you needed normalization, you could use another library to do so, before or after calling `parseUri`. That said, I'm open to adding normalization as an optional feature in future versions.
